// Home-workout hypertrophy catalog — curated for If's post-Latarjet home setup
// (10lb DBs, 15/20lb KBs, 210lb band kit, foam roller, pilates ball, shoulder pulley).
// Deliberately excludes behind-neck, wide-grip pull-ups, deep chest flys, and
// extreme-ER-under-load moves (Hindu/archer push-ups, KB snatch, handstand holds).

import type { Exercise } from "./types";

type SeedExercise = Omit<Exercise, "id" | "createdAt" | "updatedAt">;

export const HOME_EXERCISES: SeedExercise[] = [
  { name: 'Dumbbell Floor Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Floor Press', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Bottoms-up Floor Press', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Single-arm Dumbbell Floor Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Incline Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Decline Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Diamond Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Close-grip Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Wide Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tempo Push-up (3s down)', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Pseudo Planche Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Spider-Man Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Shoulder Tap Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band-resisted Push-up', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Incline Chest Press', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Decline Chest Press', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Single-arm Band Chest Press', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Chest Fly (shallow range)', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Low-to-High Fly (shallow range)', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Squeeze Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Lat Pulldown (kneeling)', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Single-arm Band Lat Pulldown', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Straight-arm Pulldown', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Bent-over Row', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Seated Row', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Single-arm Row', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Chest-supported Row', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Face Pull', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band High Row', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Reverse Fly', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Bent-over Row', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Single-arm Row', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Chest-supported Row', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Shrug', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Single-arm Row', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Renegade Row', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Inverted Row (under table)', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Scapular Retraction Hold', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Prone Swimmer', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Superman Hold', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Lateral Raise', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Front Raise', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Scaption Raise', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Rear Delt Fly', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Half-kneeling Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Single-arm Shoulder Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Z-Press (seated floor)', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Cuban Press (light)', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Arnold Press (neutral-to-neutral)', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Halo', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Bottoms-up Press', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Half-kneeling Press', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Lateral Raise', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Front Raise', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Rear Delt Fly', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Scaption Raise', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Overhead Press (neutral grip)', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Face Pull with External Rotation', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Prone Y Raise', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Prone T Raise', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Prone I Raise', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Prone W Raise', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Hammer Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Zottman Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Concentration Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Cross-body Hammer Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Reverse Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Incline Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Spider Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Drag Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell 21s', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Bicep Curl', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Bottoms-up Curl', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Bicep Curl', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Hammer Curl', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Concentration Curl', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Preacher Curl (over couch arm)', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band 21s', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Overhead Tricep Extension', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Single-arm Overhead Tricep Extension', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Tricep Kickback', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Floor Skull Crusher', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Close-grip Floor Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Tate Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Overhead Tricep Extension', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Tricep Kickback', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Overhead Tricep Extension', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Single-arm Tricep Extension', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Rope Pushdown', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bodyweight Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Pulse Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tempo Squat (5s down)', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Sumo Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Narrow Stance Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Heel-elevated Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cyclist Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Wall Sit', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Wall Sit with Tempo', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Jump Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Goblet Squat', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Goblet Squat', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Front Rack Squat', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Sumo Squat', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bulgarian Split Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Bulgarian Split Squat', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Bulgarian Split Squat', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Reverse Lunge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Forward Lunge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Lateral Lunge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Curtsy Lunge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cossack Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Cossack Squat', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Reverse Lunge', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Lateral Lunge', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Curtsy Lunge', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Pistol Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Shrimp Squat', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Box Step-up', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Deadlift', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Sumo Deadlift', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Deadlift', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Single-leg Romanian Deadlift', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Stiff-leg Deadlift', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Good Morning', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Pull-through', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Hip Thrust', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Hip Thrust', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Hip Thrust', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Glute Bridge', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Marching Glute Bridge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Clamshell', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Clamshell', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Lateral Walk', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Monster Walk', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Standing Hip Abduction', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Kickback', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Donkey Kick', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Fire Hydrant', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Nordic Hamstring Curl (assisted)', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Single-leg Calf Raise', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Calf Raise', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Seated Calf Raise (DB on knee)', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tibialis Raise (wall)', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Broad Jump', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Skater Jump', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Lateral Bound', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Split Squat Jump', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tuck Jump', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Hollow Hold', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Hollow Rock', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'V-up', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tuck-up', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Toe Touches', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Jackknife', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Russian Twist', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Weighted Russian Twist', category: 'Core', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bicycle Crunch', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Sit-up', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Weighted Sit-up', category: 'Core', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Reverse Crunch', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Lying Leg Raise', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Flutter Kick', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Scissor Kick', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Heel Tap', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Forearm Plank', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'RKC Plank (full-body tension)', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Side Plank (Left)', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Side Plank (Right)', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Side Plank Hip Dip', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Plank Shoulder Tap', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Plank to Push-up', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Copenhagen Plank', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Mountain Climber', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cross-body Mountain Climber', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Pallof Press', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Pallof Hold', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Woodchop (high-to-low)', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Reverse Woodchop (low-to-high)', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Standing Crunch', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Stir the Pot (forearms on ball)', category: 'Core', equipment: ['Pilates ball'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dead Bug with Band', category: 'Core', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Pilates Ball Dead Bug', category: 'Core', equipment: ['Pilates ball'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Suitcase Carry', category: 'Core', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Farmer Carry', category: 'Core', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'L-Sit Hold', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Hollow-to-Arch Transition', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bear Crawl', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Crab Walk', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Inchworm (no push-up)', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Turkish Half Get-up', category: 'Full Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Turkish Get-up', category: 'Full Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Thruster (warm-up first)', category: 'Full Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Burpee (no push-up)', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Clean (neutral rack)', category: 'Full Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Squat to Press', category: 'Full Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Farmer Walk', category: 'Full Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Renegade Row', category: 'Full Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: '90/90 Hip Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Couch Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'World\'s Greatest Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Quadruped T-spine Rotation', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Thread the Needle', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Wall Angel', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Spiderman Lunge with Rotation', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Frog Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Seal Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Calf Stretch at Wall', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Hamstring Floss', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll Quads', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll IT Band', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll Hamstrings', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll Lats (careful)', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll Upper Back', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roll Pecs', category: 'Mobility', equipment: ['Foam roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Hip Flexor Stretch', category: 'Mobility', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Hamstring Stretch', category: 'Mobility', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Shoulder Distraction', category: 'Mobility', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Scapular Push-up', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Wall Scapular Retraction', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Serratus Punch (supine)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Shoulder CARs (slow)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Wrist CARs', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Isometric Shoulder Flexion (wall)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Isometric Shoulder Abduction (wall)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Isometric Shoulder Internal Rotation (wall)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Isometric Shoulder External Rotation (wall)', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Band Scapular Retraction', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Side-lying External Rotation', category: 'PT/Rehab', equipment: ['Dumbbell'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Prone External Rotation at 90°', category: 'PT/Rehab', equipment: ['Dumbbell'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Resisted Scaption Raise', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Banded Sleeper Stretch (gentle)', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Pulley Assisted Flexion', category: 'PT/Rehab', equipment: ['Pulley'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Pulley Assisted Abduction', category: 'PT/Rehab', equipment: ['Pulley'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Pilates Ball Wall Push', category: 'PT/Rehab', equipment: ['Pilates ball'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Pilates Ball Scapular Squeeze', category: 'PT/Rehab', equipment: ['Pilates ball'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
];
