// AUTO-GENERATED from Notion Exercise Library export. Edit in notionExercises.ts directly if needed.
// These are all 92 exercises that existed in the user's Notion DB. Used to seed/import the app library.

import type { Exercise } from "./types";

type SeedExercise = Omit<Exercise, "id" | "createdAt" | "updatedAt">;

export const NOTION_EXERCISES: SeedExercise[] = [
  { name: 'Scapular Wall Slides', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Dumbbell Walking Lunge', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Serratus Wall Slide With Foam Roller', category: 'PT/Rehab', equipment: ['Foam roller'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Foam Roller Thoracic Extension', category: 'PT/Rehab', equipment: ['Foam roller'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Ab Roller Crunch', category: 'Core', equipment: ['Ab roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'BARBELL ROLLOUT — Ab Roller', category: 'Core', equipment: ['Barbell', 'Ab roller'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Foam Roller Back Stretch', category: 'PT/Rehab', equipment: ['Foam roller'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Foam Roller Glutes', category: 'PT/Rehab', equipment: ['Foam roller'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Foam Roller Calves', category: 'PT/Rehab', equipment: ['Foam roller'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Single-leg Glute Bridge With kb', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'B-stance kb Romanian Deadlift', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Goblet Squat', category: 'Lower Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Banded Floor Press', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Standing Band Chest Press', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Tricep Pushdown', category: 'Upper Body', equipment: ['Bands'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Overhead Tricep Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'External Rotation - Left', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'External Rotation - Right', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Wall Isometric Flexion - Left', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Resisted Standing Shoulder Extension', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Towel Flexion Wall Slide - Left', category: 'PT/Rehab', equipment: ['Towel'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Dowel-assisted Overhead Reach', category: 'PT/Rehab', equipment: ['Dowel'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Resisted Standing Row', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Dowel-assisted Standing External Rotation - Left', category: 'PT/Rehab', equipment: ['Dowel'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Dowel-assisted Standing Abduction - Lef', category: 'PT/Rehab', equipment: ['Dowel'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Resisted Eccentric External Rotation Walk Out - Left', category: 'PT/Rehab', equipment: [], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Cat-Cow Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cross-Body Shoulder Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Figure Four Glute Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Doorway Chest Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Child\'s Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Standing Hamstring Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kneeling Hip Flexor Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Standing Quad Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bird Dog', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Band Internal Rotation', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Shoulder Pulley Stretch', category: 'PT/Rehab', equipment: ['Pulley'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Band External Rotation', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Band Pull-Apart', category: 'PT/Rehab', equipment: ['Bands'], muscleGroups: [], isPT: true, isBannedLatarjet: false },
  { name: 'Dead Bug', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Running', category: 'Cardio', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Hike', category: 'Cardio', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Jump Rope', category: 'Cardio', equipment: ['Jump rope'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Barbell Jump Squat', category: 'Lower Body', equipment: ['Barbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Landmine Squat to Press', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Devil Press', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Backward Medicine Ball Throw', category: 'Full Body', equipment: ['Medicine ball'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Swings', category: 'Upper Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Human Flag', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Power Clean', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Barbell Snatch', category: 'Full Body', equipment: ['Barbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Push-up Toe Touch', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Push Press', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Romanian Deadlift', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Ski Ergometer', category: 'Cardio', equipment: ['SkiErg'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cable Hip Abduction — Cable Hip Adduction', category: 'Lower Body', equipment: ['Cable'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Burpees', category: 'Full Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Barbell Single Leg Hip Thrust', category: 'Lower Body', equipment: ['Barbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Side Plank Rotation', category: 'Core', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Frog Pump', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Ardha Kapotasana - Half Pigeon Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Dumbbell Step-up', category: 'Lower Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Camel Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Glute Bridge', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Halasana — Plow Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bridge Hip Abduction', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Malasana — Squat Pose or Garland Pose', category: 'Lower Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Kettlebell Single Leg Deadlift', category: 'Lower Body', equipment: ['Kettlebell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Adho Mukha Svanasana — Downward Facing Dog', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Barbell Glute Bridge Two Legs on Bench', category: 'Lower Body', equipment: ['Barbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Titli Asana — Butterfly Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Barbell Hip Thrusts', category: 'Lower Body', equipment: ['Barbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Balasana — Child Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Smith Machine Good Morning', category: 'Lower Body', equipment: ['Smith machine'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Tiger Yoga Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Double Arm Dumbbell Curl', category: 'Upper Body', equipment: ['Dumbbell'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Utthita Trikonasana (extended Triangle Pose)', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Brachialis Pull-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Ustrasana', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Seated Hammer Curl', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Warrior Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cable Pulldown Biceps Curl', category: 'Upper Body', equipment: ['Cable'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bhujangasana — Cobra Abdominal Stretch', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'One Leg Push-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Upavistha Konasana', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Cable Rope Overhead Triceps Extension', category: 'Upper Body', equipment: ['Cable'], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Locust Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Bench Dips', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Nauka Sanchalanasan — Rowing The Boat Pose', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'One Arm Lying Triceps Extension', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Shoulderstand — Salamba Sarvangasana', category: 'Mobility', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
  { name: 'Chin-up', category: 'Upper Body', equipment: [], muscleGroups: [], isPT: false, isBannedLatarjet: false },
];
