/**
 * Starter exercise libraries. On first login the app asks the user which one
 * to seed — "Shoulder-safe" (post-Latarjet catalog, used by If) or "Generic"
 * (a clean, common starter for people without shoulder restrictions).
 *
 * Users can edit, delete, or add exercises from the Exercises tab after seeding.
 */
import type { Exercise } from "./types";
import { findGifForName } from "./exerciseGifs";

type Seed = Omit<Exercise, "id">;

// ---------- SHOULDER-SAFE (POST-LATARJET) ----------
// Built for If: rotator-cuff-heavy PT block, bodyweight/band/light KB loads,
// explicit BANNED flags on lifts that risk the repaired shoulder.

export const SEED_EXERCISES_SHOULDER_SAFE: Seed[] = [
  // PT / Rehab (non-negotiable daily block)
  {
    name: "Shoulder Pulleys (seated, w/ heat pad)",
    category: "PT/Rehab",
    equipment: ["Shoulder rehab pulley"],
    muscleGroups: ["Rotator Cuff", "Scapular Stabilizers"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 15,
    notes: "Always exercise #1. Heat pad on left shoulder while doing pulleys.",
  },
  {
    name: "Band External Rotation (at side)",
    category: "PT/Rehab",
    equipment: ["Bands"],
    muscleGroups: ["Rotator Cuff"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 15,
    defaultWeight: 10,
  },
  {
    name: "Band Internal Rotation (at side)",
    category: "PT/Rehab",
    equipment: ["Bands"],
    muscleGroups: ["Rotator Cuff"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Scapular Wall Slides",
    category: "PT/Rehab",
    equipment: [],
    muscleGroups: ["Scapular Stabilizers"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "Prone Y-T-W Raises",
    category: "PT/Rehab",
    equipment: [],
    muscleGroups: ["Scapular Stabilizers", "Posterior Delts"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Band Pull-Aparts",
    category: "PT/Rehab",
    equipment: ["Bands"],
    muscleGroups: ["Rear Delts", "Scapular Stabilizers"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Face Pulls (light bands)",
    category: "PT/Rehab",
    equipment: ["Bands", "Door anchor"],
    muscleGroups: ["Rear Delts", "Rotator Cuff"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Serratus Push-Up (wall)",
    category: "PT/Rehab",
    equipment: [],
    muscleGroups: ["Serratus Anterior"],
    isPT: true,
    isBannedLatarjet: false,
    defaultReps: 12,
  },

  // Upper Body — shoulder-safe
  {
    name: "Tall-Kneeling Landmine Press (band)",
    category: "Upper Body",
    equipment: ["Bands", "Door anchor"],
    muscleGroups: ["Shoulders", "Chest"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Neutral-Grip Floor Press (DB)",
    category: "Upper Body",
    equipment: ["Dumbbells 10lb"],
    muscleGroups: ["Chest", "Triceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
    defaultWeight: 10,
  },
  {
    name: "Single-Arm Row (KB 20lb)",
    category: "Upper Body",
    equipment: ["Kettlebell 20lb"],
    muscleGroups: ["Lats", "Rhomboids"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
    defaultWeight: 20,
  },
  {
    name: "Chin-Up (narrow, supinated)",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Lats", "Biceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 6,
    notes: "Supinated/narrow only — wide grip is banned post-Latarjet.",
  },
  {
    name: "Band Row (seated)",
    category: "Upper Body",
    equipment: ["Bands", "Door anchor"],
    muscleGroups: ["Lats", "Rhomboids"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "DB Hammer Curl",
    category: "Upper Body",
    equipment: ["Dumbbells 10lb"],
    muscleGroups: ["Biceps", "Forearms"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
    defaultWeight: 10,
  },
  {
    name: "Band Triceps Pushdown",
    category: "Upper Body",
    equipment: ["Bands", "Door anchor"],
    muscleGroups: ["Triceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },

  // Lower Body
  {
    name: "KB Goblet Squat (20lb)",
    category: "Lower Body",
    equipment: ["Kettlebell 20lb"],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
    defaultWeight: 20,
  },
  {
    name: "KB Romanian Deadlift (20lb)",
    category: "Lower Body",
    equipment: ["Kettlebell 20lb"],
    muscleGroups: ["Hamstrings", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
    defaultWeight: 20,
  },
  {
    name: "Reverse Lunge (KB goblet 15lb)",
    category: "Lower Body",
    equipment: ["Kettlebell 15lb"],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
    defaultWeight: 15,
  },
  {
    name: "Glute Bridge (banded)",
    category: "Lower Body",
    equipment: ["Bands"],
    muscleGroups: ["Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Bulgarian Split Squat (bodyweight)",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },

  // Core
  {
    name: "Dead Bug",
    category: "Core",
    equipment: [],
    muscleGroups: ["Core", "Transverse Abdominis"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Bird Dog",
    category: "Core",
    equipment: [],
    muscleGroups: ["Core", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Pilates Ball Squeeze (supine)",
    category: "Core",
    equipment: ["Pilates ball"],
    muscleGroups: ["Transverse Abdominis", "Pelvic Floor"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Side Plank (left — be careful)",
    category: "Core",
    equipment: [],
    muscleGroups: ["Obliques"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 30,
    notes: "Static hold only. No rotation — rotation under load is banned.",
  },
  {
    name: "Side Plank (right)",
    category: "Core",
    equipment: [],
    muscleGroups: ["Obliques"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 30,
  },

  // Explicitly BANNED — pre-flagged so picker shows a red dot
  {
    name: "Behind-the-Neck Press",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Shoulders"],
    isPT: false,
    isBannedLatarjet: true,
    notes: "BANNED post-Latarjet: extreme ER under load.",
  },
  {
    name: "Wide-Grip Pull-Up",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Lats"],
    isPT: false,
    isBannedLatarjet: true,
    notes: "BANNED post-Latarjet: wide grip stresses anterior capsule.",
  },
  {
    name: "Deep Chest Fly",
    category: "Upper Body",
    equipment: ["Dumbbells 10lb"],
    muscleGroups: ["Chest"],
    isPT: false,
    isBannedLatarjet: true,
    notes: "BANNED post-Latarjet: deep horizontal abduction with load.",
  },
  {
    name: "Side Plank with Rotation",
    category: "Core",
    equipment: [],
    muscleGroups: ["Obliques"],
    isPT: false,
    isBannedLatarjet: true,
    notes: "BANNED — rotation + load on recovering shoulder. Past incident.",
  },
  {
    name: "Heavy Overhead Press (cold)",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Shoulders"],
    isPT: false,
    isBannedLatarjet: true,
    notes: "BANNED unprepped. Light OH pressing OK only with thorough RC warm-up.",
  },
];

// ---------- GENERIC (NO SHOULDER RESTRICTIONS) ----------
// Clean starter for a general lifter with home equipment (DBs, KB, bands)
// or a basic gym. No banned flags, no PT block. User can add more.

export const SEED_EXERCISES_GENERIC: Seed[] = [
  // Upper Body
  {
    name: "Push-Up",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Chest", "Triceps", "Shoulders"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "DB Bench Press",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Chest", "Triceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "DB Overhead Press",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Shoulders", "Triceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "DB Row (one arm)",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Lats", "Rhomboids"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "Pull-Up",
    category: "Upper Body",
    equipment: ["Pull-up bar"],
    muscleGroups: ["Lats", "Biceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 8,
  },
  {
    name: "Chin-Up",
    category: "Upper Body",
    equipment: ["Pull-up bar"],
    muscleGroups: ["Lats", "Biceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 8,
  },
  {
    name: "DB Bicep Curl",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Biceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "DB Hammer Curl",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Biceps", "Forearms"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "Tricep Dip (bench)",
    category: "Upper Body",
    equipment: [],
    muscleGroups: ["Triceps"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "DB Lateral Raise",
    category: "Upper Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Shoulders"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "Band Pull-Apart",
    category: "Upper Body",
    equipment: ["Bands"],
    muscleGroups: ["Rear Delts", "Rhomboids"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },

  // Lower Body
  {
    name: "Goblet Squat",
    category: "Lower Body",
    equipment: ["Kettlebell"],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 12,
  },
  {
    name: "Back Squat (barbell)",
    category: "Lower Body",
    equipment: ["Barbell"],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 8,
  },
  {
    name: "Romanian Deadlift",
    category: "Lower Body",
    equipment: ["Dumbbells"],
    muscleGroups: ["Hamstrings", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Reverse Lunge",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Bulgarian Split Squat",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Glute Bridge",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Glutes", "Hamstrings"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 15,
  },
  {
    name: "Calf Raise",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Calves"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 20,
  },
  {
    name: "Step-Up",
    category: "Lower Body",
    equipment: [],
    muscleGroups: ["Quads", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },

  // Core
  {
    name: "Plank",
    category: "Core",
    equipment: [],
    muscleGroups: ["Core"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 45,
    notes: "Reps = seconds held.",
  },
  {
    name: "Side Plank",
    category: "Core",
    equipment: [],
    muscleGroups: ["Obliques"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 30,
    notes: "Reps = seconds held.",
  },
  {
    name: "Dead Bug",
    category: "Core",
    equipment: [],
    muscleGroups: ["Core"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Bird Dog",
    category: "Core",
    equipment: [],
    muscleGroups: ["Core", "Glutes"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Hanging Knee Raise",
    category: "Core",
    equipment: ["Pull-up bar"],
    muscleGroups: ["Core", "Hip Flexors"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Russian Twist",
    category: "Core",
    equipment: [],
    muscleGroups: ["Obliques"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 20,
  },

  // Mobility / Warm-up
  {
    name: "World's Greatest Stretch",
    category: "Mobility",
    equipment: [],
    muscleGroups: ["Hips", "Thoracic Spine"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 5,
  },
  {
    name: "Cat-Cow",
    category: "Mobility",
    equipment: [],
    muscleGroups: ["Spine"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 10,
  },
  {
    name: "Hip 90/90",
    category: "Mobility",
    equipment: [],
    muscleGroups: ["Hips"],
    isPT: false,
    isBannedLatarjet: false,
    defaultReps: 8,
  },
];

export type SeedVariant = "shoulder-safe" | "generic";

export function getSeed(variant: SeedVariant): Seed[] {
  const base =
    variant === "shoulder-safe"
      ? SEED_EXERCISES_SHOULDER_SAFE
      : SEED_EXERCISES_GENERIC;
  // Prebake gifUrl from the catalog so new users see demos immediately —
  // no need to wait for the backfill hook on a later session.
  return base.map((s) => {
    const gifUrl = findGifForName(s.name);
    return gifUrl ? { ...s, gifUrl } : s;
  });
}
